// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewJournalExample.Data;

#nullable disable

namespace NewJournalExample.Migrations
{
    [DbContext(typeof(NewJournalExampleContext))]
    [Migration("20220315193547_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("NewJournalExample.Models.Comment", b =>
                {
                    b.Property<int>("CommentNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentNumber"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("JournalNumber")
                        .HasColumnType("int");

                    b.Property<int>("UserNumber")
                        .HasColumnType("int");

                    b.HasKey("CommentNumber");

                    b.HasIndex("JournalNumber");

                    b.HasIndex("UserNumber");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("NewJournalExample.Models.Journal", b =>
                {
                    b.Property<int>("JournalNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JournalNumber"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("EditorId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserNumber")
                        .HasColumnType("int");

                    b.HasKey("JournalNumber");

                    b.HasIndex("EditorId");

                    b.HasIndex("UserNumber");

                    b.ToTable("Journal");
                });

            modelBuilder.Entity("NewJournalExample.Models.User", b =>
                {
                    b.Property<int>("UserNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserNumber"), 1L, 1);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserNumber");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NewJournalExample.Models.Comment", b =>
                {
                    b.HasOne("NewJournalExample.Models.Journal", "Journal")
                        .WithMany("Comments")
                        .HasForeignKey("JournalNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NewJournalExample.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Journal");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NewJournalExample.Models.Journal", b =>
                {
                    b.HasOne("NewJournalExample.Models.User", "Editor")
                        .WithMany("EditorJournals")
                        .HasForeignKey("EditorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NewJournalExample.Models.User", "User")
                        .WithMany("Journals")
                        .HasForeignKey("UserNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Editor");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NewJournalExample.Models.Journal", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("NewJournalExample.Models.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("EditorJournals");

                    b.Navigation("Journals");
                });
#pragma warning restore 612, 618
        }
    }
}
